#!/usr/bin/env python3
"""Generate data/crates.json from a harvested crate_queue.jsonl.

The plugin's SupplyCrate BeginPlay hook logs each distinct crate class once
(`CRATE name=X` -> crate_queue.jsonl). Feed that here to classify them:

  * ArtifactCrate_N_C            -> AP LOCATION check  ("Artifact: <name>")
  * SupplyCrate_LevelNN(_Double) -> gated ITEM         ("Beacon: <color>")
  * *Cave* / *Swamp* / *Ice* / *Underwater* tiers -> gated ITEM ("Cave Crate: ...")
  * SupplyCrate_Ocean*           -> gated ITEM         ("Deep Sea Crate")
  * Beaver dams / unknown        -> ignored

`_Double` variants fold into the same gate item as their base tier (same loot
quality, just 2x). Items key the gate; artifact classes key the check.

Usage:
  python gen_crates.py <crate_queue.jsonl> [more.jsonl ...]
"""
import json
import os
import re
import sys

CRATE_ITEM_BASE = 8733000      # gated crate-access items (engrams 8730xxx, tame 8732xxx)
ARTIFACT_LOC_BASE = 8752000    # artifact checks (notes 8740xxx, bosses 8750xxx, milestones 8751xxx)

HERE = os.path.dirname(__file__)
OUT = os.path.normpath(os.path.join(HERE, "..", "data", "crates.json"))
BUNDLED = os.path.normpath(os.path.join(HERE, "..", "apworld", "ark_ase", "data", "crates.json"))

ARTIFACT_NAMES = {
    1: "Hunter", 2: "Pack", 3: "Massive", 4: "Devious", 5: "Clever", 6: "Skylord",
    7: "Devourer", 8: "Immune", 9: "Strong", 10: "Cunning", 11: "Brute",
}
BEACON_COLORS = {
    "03": "White", "15": "Green", "25": "Blue", "35": "Purple", "45": "Yellow", "60": "Red",
}


def main() -> None:
    if len(sys.argv) < 2:
        sys.exit("usage: gen_crates.py <crate_queue.jsonl> [more.jsonl ...]")

    names = []
    seen = set()
    for src in sys.argv[1:]:
        with open(src, encoding="utf-8") as fh:
            for line in fh:
                n = line.strip().strip('"')
                if n and n not in seen:
                    seen.add(n)
                    names.append(n)

    artifacts = {}                 # artifact number -> set of classes
    gated = {}                     # canonical gate label -> {"ap_name", "classes": set}
    ignored = []

    for n in names:
        m = re.search(r"ArtifactCrate_(\d+)_C", n)
        if m:
            artifacts.setdefault(int(m.group(1)), set()).add(n)
            continue
        m = re.search(r"SupplyCrate_Level(\d+)", n)
        if m:
            lvl = m.group(1).zfill(2)
            color = BEACON_COLORS.get(lvl, "Lvl" + lvl)
            key = "beacon_" + lvl
            gated.setdefault(key, {"ap_name": f"Beacon: {color}", "classes": set()})["classes"].add(n)
            continue
        if re.search(r"Ocean", n):
            gated.setdefault("deepsea", {"ap_name": "Deep Sea Crate", "classes": set()})["classes"].add(n)
            continue
        m = re.search(r"(Swamp|Ice|Underwater)?Cave\w*?Tier(\d+)", n)
        if m:
            cave = m.group(1) or "Cave"
            tier = m.group(2)
            key = f"cave_{cave}_{tier}".lower()
            label = {"Swamp": "Swamp Cave", "Ice": "Ice Cave",
                     "Underwater": "Underwater Cave", "Cave": "Cave"}[cave]
            gated.setdefault(key, {"ap_name": f"Cave Crate: {label} T{tier}", "classes": set()})["classes"].add(n)
            continue
        ignored.append(n)

    crate_items = []
    for i, key in enumerate(sorted(gated)):
        g = gated[key]
        crate_items.append({"id": CRATE_ITEM_BASE + i, "ap_name": g["ap_name"],
                            "classes": sorted(g["classes"])})

    artifact_locations = []
    for i, num in enumerate(sorted(artifacts)):
        nm = ARTIFACT_NAMES.get(num, f"#{num}")
        artifact_locations.append({"id": ARTIFACT_LOC_BASE + i,
                                   "name": f"Artifact: {nm}",
                                   "classes": sorted(artifacts[num])})

    out = {
        "_comment": f"Generated by gen_crates.py: {len(crate_items)} gated crate items "
                    f"+ {len(artifact_locations)} artifact checks. classes = runtime GetFullName "
                    f"prefixes harvested by the SupplyCrate BeginPlay hook. ignored: {ignored}",
        "_id_base_items": CRATE_ITEM_BASE,
        "_id_base_locations": ARTIFACT_LOC_BASE,
        "crate_items": crate_items,
        "artifact_locations": artifact_locations,
    }
    for path in (OUT, BUNDLED):
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as fh:
            json.dump(out, fh, indent=2)
        print(f"wrote {len(crate_items)} crate items + {len(artifact_locations)} artifacts -> {path}")
    if ignored:
        print("ignored (not classified):", ignored)


if __name__ == "__main__":
    main()
