#!/usr/bin/env python3
"""Rebuild data/spawn_classes.json from REAL harvested dino class names.

The randomize_dino_spawns shuffle uses Game.ini NPCReplacements, which match on the exact
Character_BP class name. The original list was wiki-guessed and mostly wrong (empty spawns).
The plugin (v73+) harvests the real names: run '/dumpdinos' in-game around spawn zones and/or
'cheat DestroyWildDinos', which writes each real class to ArkAP_dino_classes.jsonl.

  python tools/gen_spawn_classes.py <ArkAP_dino_classes.jsonl> [more.jsonl ...]

Feed that harvest file here. This classifies each class into a habitat group (for 'grouped'
mode) and drops non-wild / boss / alpha / tek / special classes, then writes both copies of
spawn_classes.json. Review the output - unknowns default to 'land' and are listed so you can
correct WATER_KEYS / AIR_KEYS / EXCLUDE below.
"""
import json
import os
import sys

HERE = os.path.dirname(__file__)
OUT = os.path.normpath(os.path.join(HERE, "..", "data", "spawn_classes.json"))
BUNDLED = os.path.normpath(os.path.join(HERE, "..", "apworld", "ark_ase", "data", "spawn_classes.json"))

# class-name substrings that mark a class as NOT a normal wild spawn to shuffle.
# alphas are the Mega* predators + ocean Mega_/_Mega; bosses/tek/minions/event variants excluded.
EXCLUDE = (
    "Boss", "Tek", "Minion", "Corrupt", "Eden", "Gauntlet", "Escort", "_VR", "Character_BP_Aggressive",
    "MegaRaptor", "MegaCarno", "MegaRex", "Mega_", "_Mega", "Alpha", "Retrieve", "Summon",
    "Baby", "Gen2", "Bog", "Ocean", "STA_", "Race", "Hunt", "Mission",
    "Titanosaur", "Bee_Character",  # map-limited mega spawn / hive mechanic (kept out on purpose)
)

# habitat classification by class-name substring. Everything not matched = land.
WATER_KEYS = (
    "Coel", "Dolphin", "Ichthyosaur", "Megalodon", "Mosa", "Plesiosaur", "Angler", "Manta",
    "Dunkle", "Basilo", "Leech", "Trilobite", "Eel", "Electrophorus", "Cnidaria", "Jellyfish",
    "Euryp", "Salmon", "Piranha", "Tuso", "Liopleurodon", "Diplocaulus", "Ammonite", "Otter",
    "Hesperornis", "Sabertooth_Salmon", "Lamprey",
)
AIR_KEYS = (
    "Ptero", "Argent", "Pela", "Dimorph", "Bat", "Ichthyornis", "Quetz", "Tapejara", "Rhynio",
    "Vulture", "Microraptor", "Archa",   # Microraptor/Archaeopteryx glide - treat as air-ish
)


def habitat(cls: str) -> str:
    low = cls.lower()
    if any(k.lower() in low for k in WATER_KEYS):
        return "water"
    if any(k.lower() in low for k in AIR_KEYS):
        return "air"
    return "land"


def pretty(cls: str) -> str:
    # "Raptor_Character_BP_C" -> "Raptor"
    name = cls
    for suf in ("_Character_BP_C", "_Character_C", "_Character_BP", "_C"):
        if name.endswith(suf):
            name = name[: -len(suf)]
            break
    return name


def main() -> None:
    if len(sys.argv) < 2:
        sys.exit("usage: gen_spawn_classes.py <ArkAP_dino_classes.jsonl> [more.jsonl ...]")

    classes = []
    seen = set()
    for src in sys.argv[1:]:
        with open(src, encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    cls = json.loads(line)["class"]
                except Exception:
                    continue
                if cls and cls not in seen:
                    seen.add(cls)
                    classes.append(cls)

    kept, dropped = [], []
    for cls in sorted(classes):
        if any(x in cls for x in EXCLUDE) or "_Character_BP" not in cls:
            dropped.append(cls)
            continue
        kept.append({"name": pretty(cls), "class": cls, "habitat": habitat(cls)})

    by_hab = {"land": 0, "water": 0, "air": 0}
    for e in kept:
        by_hab[e["habitat"]] += 1

    out = {
        "_comment": f"Generated by gen_spawn_classes.py from {len(classes)} harvested classes "
                    f"({len(kept)} kept / {len(dropped)} excluded). habitat groups keep 'grouped' "
                    f"mode sane (land<->land, water<->water, air<->air). Class names are HARVESTED "
                    f"from the live server (ArkAP_dino_classes.jsonl), not guessed.",
        "spawn_classes": kept,
    }
    for path in (OUT, BUNDLED):
        with open(path, "w", encoding="utf-8") as fh:
            json.dump(out, fh, indent=2)
        print(f"wrote {len(kept)} classes ({by_hab}) -> {path}")
    print(f"\nExcluded {len(dropped)}:")
    for c in dropped:
        print("  ", c)
    print("\nReview 'land' classifications for anything aquatic/flying that slipped through, "
          "and adjust WATER_KEYS / AIR_KEYS / EXCLUDE at the top of this script if needed.")


if __name__ == "__main__":
    main()
