#!/usr/bin/env python3
"""Generate data/engrams.json from an ArkAP.DumpEngrams dump.

The plugin's engram gate keys on UClass GetFullName (= the dump's "item_class"),
so engram_class in our json must equal that exact string.

Usage:
  python gen_engrams.py <dump.json> [--count N] [--all]
    --count N : take the first N engrams (default 12, the early-game slice)
    --all     : take every engram in the dump
"""
import argparse
import json
import os
import re

ID_BASE = 8730001
# (legacy "Taming Unlocked"/"Supply Crate Access" removed - superseded by per-dino tames + per-crate
#  access; they were no-op items in the pool.)
SPECIAL = []

# Default engrams ARK auto-grants (level 1) - never gate these. Matched against the
# stripped entry name (case-insensitive). Add more as needed.
EXCLUDE = {"note", "notepaper", "stonepick", "torch"}

# Saddle engrams for creatures NOT on The Island (other-map/DLC dinos) -> useless checks, dropped.
# Matched against the final "Engram: <name>" ap_name. Platform/Tek variants of OWNED creatures are
# kept (Sauro/Quetz/Plesio/Paracer/Mosa Platform, Tek Rex/Mosa/Megalodon/Tapejara).
EXCLUDE_ENGRAMS = {
    "Engram: Basilisk Saddle", "Engram: Cherufe Saddle", "Engram: Gacha Saddle", "Engram: Gas Bags Saddle",
    "Engram: Giant Turtle Saddle", "Engram: Ice Jumper Saddle", "Engram: Karkino Saddle",
    "Engram: Milkglider Saddle", "Engram: Owl Saddle", "Engram: Ravager Saddle", "Engram: Rollrat Saddle",
    "Engram: Saddle Amarga", "Engram: Saddle Andrewsarchus", "Engram: Saddle Camelsaurus",
    "Engram: Saddle Deinonychus", "Engram: Saddle Desmodus", "Engram: Saddle Mantis", "Engram: Saddle Moth",
    "Engram: Saddle Rock Golem", "Engram: Saddle Spiney Lizard", "Engram: Saddle Tropeognathus",
    "Engram: Shadow Drake Saddle", "Engram: Space Dolphin Saddle", "Engram: Spindles Saddle",
    "Engram: Tek Rock Drake Saddle", "Engram: Tek Space Whale Saddle",
    # Scorched Earth / other-map non-saddle engrams not craftable on The Island.
    "Engram: Clay", "Engram: Tent", "Engram: Vessel", "Engram: Wind Turbine",
}

# substring-matched engram exclusions (whole categories from other maps).
EXCLUDE_ENGRAM_SUBSTR = {"Adobe", "Desert Cloth", "Hazard Suit"}

HERE = os.path.dirname(__file__)
OUT = os.path.normpath(os.path.join(HERE, "..", "data", "engrams.json"))
BUNDLED = os.path.normpath(os.path.join(HERE, "..", "apworld", "ark_ase", "data", "engrams.json"))


def pretty(entry_name: str) -> str:
    s = re.sub(r"^EngramEntry_?", "", entry_name)
    s = re.sub(r"_C(_\d+)?$", "", s)
    s = s.replace("_", " ")
    s = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", " ", s)   # split CamelCase
    return s.strip()


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("dump")
    ap.add_argument("--count", type=int, default=12)
    ap.add_argument("--all", action="store_true")
    a = ap.parse_args()

    with open(a.dump, encoding="utf-8") as fh:
        dump = json.load(fh)

    # drop auto-granted default engrams first, then slice
    dump = [e for e in dump if pretty(e["entry_name"]).replace(" ", "").lower() not in EXCLUDE]
    if not a.all:
        dump = dump[: a.count]

    engrams = []
    for e in dump:
        ap_name = "Engram: " + pretty(e["entry_name"])
        if ap_name in EXCLUDE_ENGRAMS or any(s in ap_name for s in EXCLUDE_ENGRAM_SUBSTR):
            continue                            # drop other-map engrams (useless checks/items)
        engrams.append({
            "id": ID_BASE + len(engrams),        # sequential, no gaps after excludes
            "ap_name": ap_name,
            "engram_class": e["item_class"],   # full GetFullName string - must match in-game
            "tier": "auto",
        })

    out = {
        "_comment": f"Generated by gen_engrams.py from {os.path.basename(a.dump)} "
                    f"({len(engrams)} engrams). engram_class = UClass GetFullName, matched by the plugin.",
        "_id_base": ID_BASE,
        "engrams": engrams,
        "_special_id_base": 8739000,
        "special_items": SPECIAL,
    }
    for path in (OUT, BUNDLED):
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as fh:
            json.dump(out, fh, indent=2)
        print(f"wrote {len(engrams)} engrams -> {path}")


if __name__ == "__main__":
    main()
